### ISSUE TITLE
Problems building on Raspberry

### ISSUE THREAD

**Issue by AlessandroMelino** [spencer-project/spencer_people_tracking#94]
Hello, I am trying to install from source the package on a Raspberry pi 4 with Raspberry PI OS (64 bits) and ROS Noetic.

Trying to build it with `catkin config --init --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo` the following error appears:

```
Traceback (most recent call last):
  File "/usr/bin/catkin", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'trollius' distribution was not found and is required by catkin-tools
```

On the other hand, trying to build it with `catkin_make` the following error appears:

```
make[2]: *** No rule to make target '/usr/lib/aarch64-linux-gnu/libOpenGL.so', needed by '/home/pi/catkin_ws/devel/lib/libtrack_annotation_tool_rviz_plugin.so'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:12017: spencer_people_tracking/utils/track_annotation_tool/CMakeFiles/track_annotation_tool_rviz_plugin.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** No rule to make target '/usr/lib/aarch64-linux-gnu/libOpenGL.so', needed by '/home/pi/catkin_ws/devel/lib/libspencer_tracking_rviz_plugin.so'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:11694: spencer_people_tracking/visualization/spencer_tracking_rviz_plugin/CMakeFiles/spencer_tracking_rviz_plugin.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
Invoking "make -j4 -l4" failed
```

How can I solve this and build it in one of both ways?

Best regards.
Alessandro

**Comment by sadiq26** [comment]
How did you solve this? Stuck on same issue on Raspberry Pi  4(8GB) with ROS Noetic
